---
- name: Create Jenkins folders
  file:
    path: "{{ item }}"
    owner: "{{ jenkins_owner_id }}"
    group: "{{ jenkins_group_id  }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ jenkins_home_directory }}"
  tags:
    - configuration
  become: true

- name: Start jenkins container
  docker_container:
    name: jenkins
    image: "{{ jenkins_docker_image }}:{{ jenkins_docker_image_tag }}"
    state: started
    exposed_ports:
      - 8080
      - 50000
    published_ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "{{ jenkins_home_directory }}:/var/jenkins_home:rw"
  become: true

# TODO: finish setting this up:
# - name: Create plugins.txt
#   template:
#     dest: /var/jenkins_home/plugins.txt
#     src: var/jenkins_home/plugins.txt.j2
#     owner: "{{ jenkins_user }}"
#     group: "{{ jenkins_group }}"
#   notify: Install Jenkins Plugins
#   become: true