---

- name: Start jenkins container
  docker_container:
    name: jenkins
    image: "{{ jenkins_docker_image }}"
    state: started
    exposed_ports:
      - 8080
      - 50000
    published_ports:
      - 8080:8080
      - 5000:5000