---

- include: "{{ ansible_os_family|lower }}/setup.yml"

- name: Install python dependencies
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    state: present
  with_dict: "{{ python_requirements }}"
  become: true


- name: Install Docker.
  package: 
    name: "{{ docker_package }}"
    state: present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes
