---

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install python dependencies
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    state: present
  with_dict: "{{ python_requirements }}"
  become: true


- name: Install Docker.
  package: name={{ docker_package }} state={{ docker_package_state }}

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes
