---

- name: install plex
  include_tasks: apt.yml

- name: 'Create media directories'
  file:
    path: "{{ library_path }}/{{ item }}"
    state: directory
    owner: plex
    recurse: yes
  with_items:
    - movies
    - series
    - music

- name: Update UFW
  import_tasks: ufw.yml

- name: create samba share
  import_tasks: samba.yml
  tags:
    - fileshare

- name: create media folders
  file:
    path: "{{ media_share_path }}/{{ item }}"
    state: directory
  with_items:
    - Movies
    - Television
    - Music


- meta: flush_handlers
