---
- name: install samba packages
  apt: 
    name: "{{ item }}"
  with_items:
    - samba-server
    - samba-common
  become: true

- name: configure samba share

- name: start samba and enable on boot
  service:
    name: samba
    state: started
    enabled: yes