---
- name: install samba packages
  apt: 
    name: "{{ samba_packages }}"
  become: true

# - name: configure samba share

- name: start samba and enable on boot
  service:
    name: samba
    state: started
    enabled: yes