---
- name: install samba packages
  apt: 
    name: "{{ samba_packages }}"
  become: true

- name: unmask samba
  systemd:
    name: samba
    masked: no

- 


- name: start samba and enable on boot
  service:
    name: "{{ debian_samba_service_name }}"
    enabled: yes
    state: started
