---
- name: Configure server
  hosts: jenkins
  roles:
    - git
    - mongrelion.docker

- name: download and run docker container
  hosts: jenkins_master
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    exposed_ports:
      - 8080
      - 50000


