---
- hosts: jenkins_masters
  become: true
  roles:
    - role: base
      tags:
        - dependencies
    - role: docker
      tags:
        - dependencies
    - role: jenkins_master
      tags:
        - container
    - role: nginxinc.nginx
      tags:
        - nginx


