---
- hosts: jenkins_master
  roles:
    - git
    - mongrelion.docker
  tasks:
    - name: download and run docker container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: present
        exposed_ports:
          - 8080
          - 50000


