---
- hosts: "{{ host | default('web') }}"
  remote_user:
  become: true
  tasks:
  # TODO: add a step that checks for firewall status, opens proper ports.
    - name: add software-properties-common
      apt:
        name: software-properties-common
        state: present
    - name: add certbot repository
      apt_repository:
        repo: ppa:certbot/certbot
        state: present
    - name: update apt
      apt:
        upgrade: dist
    - name: install certbot for nginx
      apt:
        name: python-certbot-nginx